### ISSUE TITLE
Extend Temp File and Directory classes

### ISSUE THREAD

**Issue by miroslavpojer** [AbsaOSS/commons#117]
Extend TempFile and TempDirectory classes to get stable outputs when using on different Operation Systems.
On Windows additional actions are needed to reach code behavior similar to unix.

**Comment by wajda** [comment]
> On Windows additional actions are needed...

What exact problem is going to be solved here?

**Comment by miroslavpojer** [comment]
> > On Windows additional actions are needed...
> 
> What exact problem is going to be solved here?

This issue should add features to provide stable output on different operation systems. Multiple projects work with Temp* classes and have to solve compatibility between unix vs windows in unit tests.

**Comment by wajda** [comment]
Can you be more specific? From the PR I guess the aim is to guarantee the canonical representation of the path string returned by `toString()` that is equal on both platforms . What else?

**Comment by miroslavpojer** [comment]
> Can you be more specific? From the PR I guess the aim is to guarantee the canonical representation of the path string returned by `toString()` that is equal on both platforms . What else?

Sure. 
Issue should solve problems found when running unit-tests on windows where:

- assert comparison are failing due: used `\` directory separators on windows OS. 
- provide `toURI` method to avoid multiple possible ways of conversion from Temp* class's path member.

**Comment by miroslavpojer** [comment]
Received tips for renaming the new methods to keep `toString` method not touched.

**Comment by miroslavpojer** [comment]
Issue can be closed as 1st PR has been merged and 2ns removed.
