### ISSUE TITLE
asOption method ambiguity

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/commons#123]
```Scala
import za.co.absa.commons.lang.extensions.NonOptionExtension._

"A".asOption // Some(A)
Seq(1, 2).asOption // Some(List(1, 2))
Seq().asOption // Some(List())
```

```Scala
import za.co.absa.commons.lang.extensions.NonOptionExtension._
import za.co.absa.commons.lang.extensions.TraversableExtension._

"A".asOption // Some(A)
Seq(1, 2).asOption // Some(List(1, 2))
Seq().asOption // None
```

The problem here is `asOption` from `TraversableExtension` has the same name even though it is doing something little bit different. I think best way to solve this would be rename the `asOption` to `asFlatOption` or `asFloption` or something similar.
The problem of course is that renaming would break backward compatibility.

**Comment by wajda** [comment]
`asNonEmptyOption` (similarly to String implicits) and deprecate the current one?
