### ISSUE TITLE
Version: add SemVer specific methods

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/commons#13]
Naturally one would expect to be able to get _major_, _minor_, _patch_ version or other components from a `Version` object after explicitly parsing it as a _Semantic Version_.

### Proposal:
```scala
semver"1.2.3-beta+meta".major      // returns 1
semver"1.2.3-beta+meta".minor      // returns 2
semver"1.2.3-beta+meta".patch      // returns 3

semver"1.2.3-beta+meta".core       // returns Version.asSemVer(1, 2, 3)
semver"1.2.3-beta+meta".preRelease // returns Version.asSimple("beta")
semver"1.2.3-beta+meta".buildMeta  // returns Version.asSimple("meta")
```

Currently it won't work as both `ver` and `semver` interpolators return the same `Version` object that is a spec agnostic.

**Comment by dk1844** [comment]
The proposal makes perfect sense to me. 
If I were a stranger using the API for the first time, I'd probably look for something containing the word `final` to get the `truncateLabels` functionality, though (`finalVersion`, `final`, ...?). Maybe such an alias could exist for `truncateLabels`?

**Comment by wajda** [comment]
There is no term "final" in the spec :) They call it "normal" - https://semver.org/#semantic-versioning-specification-semver
Should we call the method the way? It just looked odd to me, that why I used "trancateLabels" instead. On the other hand, if the spec calls it that way then why shouldn't we?

**Comment by yruslan** [comment]
They don't define this in the spec, but in the Backus–Naur Form the have `version core`. So maybe `.versionCore`?
