### ISSUE TITLE
Json4s: Ensure byte code compatibility with Json4s 3.6.7

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/commons#27]
Currently, there is at least one problem with a library required by Spark. 3.0.0

Different versions of Spark use different json4s versions. In this case the problem is caused by changes between 3.5.5 and 3.6.7 (used by Spark 3)

```
java.lang.NoSuchMethodError: org.json4s.Formats.$plus$plus(Lscala/collection/Traversable;)Lorg/json4s/Formats;
	at za.co.absa.commons.json.format.JavaTypesSupport.formats(JavaTypesSupport.scala:23)
```

We should fix mentioned problem and also check and fix all compatibility problem with Spark 3 that we can find.

**Comment by wajda** [comment]
A minor thing - the issue isn't related to Spark but Json4s. Let's rename it to avoid confusion.

**Comment by cerveada** [comment]
It is. I think we should check that we are compatible with Spark 3 basically. The problem I described is one instance where we are not, but we should fix all problems not just that one.

**Comment by wajda** [comment]
How is it related to Commons then? Do you want to develop a universal Spark adapter?

**Comment by uday1409** [comment]
I have tested the spark 3.0 compatibility after making changes to commons and spark agent. Two things we need to change

1) Spark 3.0 supports json4s 3.6.6, and created a pull request for the same to commons.

2) Spark agent should refer appropriate commons version based on spark version, handled it using profiles. I will create a pull request but versioning is not proper as commons needs to be published with Spark3.0 changes

**Comment by wajda** [comment]
Thanks @uday1409 
I still see a confusion between this issue and AbsaOSS/spline-spark-agent#93.
The `commons` jar consists of several logically independent packages, each with its own limited set of non-transitive dependencies.

Specifically the package `za.co.absa.commons.spark` contains some Spark schema utils, hence depends on `spark-sql`, while the package `za.co.absa.commons.json` only contains JSON utils, thus depends on `json4s`. They are independent! 

The `Spark 3.0 + Json4s` problem lies outside of `commons` project. Particularly here we are talking about binary incompatibility issue occurring in the Spline agent, that uses `za.co.absa.commons.json` adapters. So this issue should be solved in the place of usage - the Spline agent. `commons` has nothing to do with Spark 3.0

**Comment by wajda** [comment]
I have put together a small dumy project to test different `za.co.absa.commons.json` SerDe in different combinations of Scala and Json4s version.

https://github.com/AbsaOSS/commons/issues/27

The test passed in all permutations of Scala 2.11, 2.12 and Json4s 3.2, 3.5, 3.6
So I still have yet to reproduce the issue in isolation.

**Comment by wajda** [comment]
Reproduced it in Json4s 3.6
```scala
new DefaultJacksonJsonSerDe with JavaTypesSupport
```
